language: ruby

rvm:
- 2.3.0

before_script:
- chmod +x ./script/cibuild

script:
- bundle exec jekyll build

branches:
  only:
  - master
  
deploy:
  provider: s3
  access_key_id: AKIAISOXU25IVQ24VJVA
  secret_access_key:
    secure: b5/IXQG4QQbmHEt1hZt3vpZzkaEolAkiN+pcHoeA9fsE9+hmh2JXBkDDgDHNL+e0zAX2F0RSq67EJkXaau7wohbT0qcz3WQUSUGC8QNsDP+Iy/Jw1yY4LcVTV9WIf3Rp+IHeLOkOrjC9zcowi/EsH9vxWRReFDgHH8r+QDj8WMzblIM+wqDvV4q98No/y4Zw9i/UW5imEf5R4mjEhMeoZFe6jXWISe5FmwwteIwheKU6yv0lJNLG2QYEhEy6JfYiBLjzMD/Q+NHuGsPyCxDxYp+AG4GoVj9KjUemuPENiDxok8Qmb72n662nnbvcxnBMi8LZQcKPc3oymupJu3Yj0wWoOSv+THoySE1RWOuYCBoBc0P1kkuWCxciEe8CMKN0zkK+zVYcksOgbbUu23WFKmX8VmMeMv6a9lBXbQ1MdgjJRPzG590wnxV/avKKUivruZsTRqZreYBsR2v8zmfd0FlzCuM3ODz60Z9D3YMGwzhBSMP6g6/IW1HVhdjYVci0vgx5nqyGtx4wWk2lHORzAI3VvGeZ/lSOwmyk2Vk5NSHGB1qKy/21ve7uEUruvGSKM0aQn35YQ0J0AMUhxjDARxckmTcOzcIaTbDcd3kC0SuWP0mZrH1U0ZcauLAJnY783RSjKBwGTfBFtnymHGfPxmzvlUgX6QpsS1plHEOUpxI=
  bucket: www.cachy.me
  local-dir: _site
  acl: public_read
  region: eu-west-2
  skip_cleanup: true
  on:
    repo: devoctomy/cachy.me
