language: ruby

rvm:
- 2.3.0

before_script:
- chmod +x ./script/cibuild

script: "./script/cibuild"

branches:
  only:
  - master
  
deploy:
  provider: s3
  access_key_id: AKIAISOXU25IVQ24VJVA
  secret_access_key:
    secure: "R775l7xTZYyESrr8ioswhg1xR7Br7GYoUFA3LE69D9qZG6qcihjGwDwlqxEH1gx4E9bSHhZq5RkksgQg1JSc4whZPxw4S6WfjDn7nViBrGcUh/BeGnk1EkhiG7sMBpzaw4nGHRuviRhwxw/X28fnAwZq6WTIN47jNY9quXbZraIKtcPnCqdTuDjQjxzLW85Cqz068rHtayBvEI410d+8BLl5rgtz4Yy6AJQST/zkhcECYDCHbdJUAhTm63yY7futiaHek2Hjk35fUrE3433BNg3+fE3CPL4dkd1aT+7pcwR5CofCpNa+tYTEB/Irm1yldQd0VT92WCH7PTeUJGXMmeE64W6hTXVYRSlN6oq3NlNPWjwdYbKuN6LJyYDUuc6MHxY9ePkATBet2wSqjqh0D7mJ+8OUaeEUntHRqaFbLR7HuzCPft3eE8tYnQvRewrKRG6TjMSx9EZrjN0wNLCsTcgtw7jc04ZO1DE88/f7XpybcnunEzL9Q68QzYLsBLrpmpVzv/fAsOEmdDuJeG5QD6sd/n6qknc8BI7XpfujMBgMtcxRlcZyvMXYFtVRSQtKl4SSua4GOcgn7OFkJH3HWRjrmy6IRW3xRK406zvt4a7oewkscOIZKiTCVilWImcyKtYI9ZGkGfTOAoj2dvN8XDvxiSVgUv6f8TmP7t7OmcM="
  bucket: www.cachy.me
  local-dir: _site
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  on:
    repo: devoctomy/cachy.me
