title: cachy
description: Cross-Platform Password Protection System
email: support@devoctomy.com
paginate: 10
social:
  twitter: https://www.twitter.com/devoctomy
  facebook: https://www.facebook.com/cachyapp

# Build settings
include: ["_categories"]
exclude: ["Gemfile", "Gemfile.lock", "vendor"]
markdown: kramdown
  
gems: [jekyll-paginate, travis]