title: cachy
description: Cross-Platform Password Protection System
email: support@devoctomy.com
googltagtrackingid: UA-69539327-6
social:
  twitter: https://www.twitter.com/devoctomy
  facebook: https://www.facebook.com/cachyapp

# Build settings
include: ["_categories"]
exclude: ["Gemfile", "Gemfile.lock", "vendor"]
markdown: kramdown
  
plugins: [travis]